package:
    name: pyg-cell
    version: 0.0.2

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base          >=0.0.17
    run:
        - pyg-base          >=0.0.17
        
about:
    home: https://github.com/gityoav/pyg-cell
    license: GNU