package:
    name: pyg-cell
    version: 0.0.1

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base          >=0.0.17
        - pyg-mongo         >=0.0.11
        - pyg-sql           >=0.0.1
    run:
        - pyg-base          >=0.0.17
        - pyg-mongo         >=0.0.11
        - pyg-sql           >=0.0.1
        
about:
    home: https://github.com/gityoav/pyg-cell
    license: GNU